### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by strlcat** [tnakamur/android_manifest_google_sunfish#1]
I'm trying to build an twrp-11 branch and I get error that product doesn't exist:
```
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "omni_sunfish".
23:01:55 dumpvars failed with: exit status 1
WARNING: Trying to fetch a device that's already there
Traceback (most recent call last):
  File "vendor/twrp/build/tools/roomservice.py", line 431, in <module>
    fetch_device(device)
  File "vendor/twrp/build/tools/roomservice.py", line 399, in fetch_device
    git_data = search_gerrit_for_device(device)
  File "vendor/twrp/build/tools/roomservice.py", line 86, in search_gerrit_for_device
    device_data = check_repo_exists(git_data, device)
  File "vendor/twrp/build/tools/roomservice.py", line 63, in check_repo_exists
    "exiting roomservice".format(device=device))
Exception: sunfish not found,exiting roomservice
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "omni_sunfish".
23:01:56 dumpvars failed with: exit status 1

** Don't have a product spec for: 'omni_sunfish'
** Do you have the right repo manifest?

```

And there is only `aosp_sunfish` I suppose. But it bails out with errors:
```
[100% 23/23] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: system/tools/hidl/test/vendor/1.1/Android.bp:3:1: "hidl.tests.vendor@1.1-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/graphics/allocator/2.0/Android.bp:3:1: "android.hardware.graphics.allocator@2.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/contexthub/1.0/Android.bp:3:1: "android.hardware.contexthub@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/wifi/1.2/Android.bp:3:1: "android.hardware.wifi@1.2-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/input/classifier/1.0/Android.bp:3:1: "android.hardware.input.classifier@1.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/gnss/measurement_corrections/1.1/Android.bp:3:1: "android.hardware.gnss.measurement_corrections@1.1-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/keymaster/4.0/Android.bp:3:1: "android.hardware.keymaster@4.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/camera/device/3.2/Android.bp:3:1: "android.hardware.camera.device@3.2-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/automotive/audiocontrol/1.0/Android.bp:3:1: "android.hardware.automotive.audiocontrol@1.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/wifi/hostapd/1.1/Android.bp:3:1: "android.hardware.wifi.hostapd@1.1-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: system/libhidl/transport/memory/token/1.0/Android.bp:3:1: "android.hidl.memory.token@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/camera/metadata/3.2/Android.bp:3:1: "android.hardware.camera.metadata@3.2-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/graphics/common/1.2/Android.bp:3:1: "android.hardware.graphics.common@1.2-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/vr/1.0/Android.bp:3:1: "android.hardware.vr@1.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/tests/msgq/1.0/Android.bp:3:1: "android.hardware.tests.msgq@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/camera/device/1.0/Android.bp:3:1: "android.hardware.camera.device@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: frameworks/hardware/interfaces/automotive/display/1.0/Android.bp:3:1: "android.frameworks.automotive.display@1.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/camera/provider/2.4/Android.bp:3:1: "android.hardware.camera.provider@2.4-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/soundtrigger/2.0/Android.bp:3:1: "android.hardware.soundtrigger@2.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/neuralnetworks/1.1/Android.bp:3:1: "android.hardware.neuralnetworks@1.1-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/tetheroffload/config/1.0/Android.bp:3:1: "android.hardware.tetheroffload.config@1.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/audio/4.0/Android.bp:3:1: "android.hardware.audio@4.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/vibrator/1.0/Android.bp:3:1: "android.hardware.vibrator@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/camera/common/1.0/Android.bp:3:1: "android.hardware.camera.common@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/radio/deprecated/1.0/Android.bp:3:1: "android.hardware.radio.deprecated@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/vibrator/1.1/Android.bp:3:1: "android.hardware.vibrator@1.1-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/wifi/1.0/Android.bp:3:1: "android.hardware.wifi@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/cas/native/1.0/Android.bp:3:1: "android.hardware.cas.native@1.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: system/hardware/interfaces/net/netd/1.0/Android.bp:3:1: "android.system.net.netd@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/tests/hash/1.0/Android.bp:3:1: "android.hardware.tests.hash@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/drm/1.0/Android.bp:3:1: "android.hardware.drm@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/gnss/2.1/Android.bp:3:1: "android.hardware.gnss@2.1-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/weaver/1.0/Android.bp:3:1: "android.hardware.weaver@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/google/interfaces/media/c2/1.0/Android.bp:3:1: "hardware.google.media.c2@1.0-vts.driver" depends on undefined module "VtsHalDriverDefaults"
error: hardware/interfaces/media/1.0/Android.bp:3:1: "android.hardware.media@1.0-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/graphics/common/1.1/Android.bp:3:1: "android.hardware.graphics.common@1.1-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
error: hardware/interfaces/radio/config/1.1/Android.bp:3:1: "android.hardware.radio.config@1.1-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: system/hardware/interfaces/wifi/keystore/1.0/Android.bp:3:1: "android.system.wifi.keystore@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/tests/foo/1.0/Android.bp:3:1: "android.hardware.tests.foo@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/camera/metadata/3.3/Android.bp:3:1: "android.hardware.camera.metadata@3.3-vts.profiler" depends on undefined module "VtsHalProfilerDefaults"
23:04:12 soong bootstrap failed with: exit status 1

#### failed to build some targets (6 seconds) ####

```
Did you succeeded at building TWRP for sunfish? Can you point me in the right direction?

I used commands given in README.md of twrp-11 branch repo.

**Comment by tnakamur** [comment]
Do you set 'ALLOW_MISSING_DEPENDENCIES=true'?
I suceeded at building TWRP for sunfish, use twrp-11 branch.

**Comment by strlcat** [comment]
> Do you set 'ALLOW_MISSING_DEPENDENCIES=true'?
> I suceeded at building TWRP for sunfish, use twrp-11 branch.

Thank you very much! I now have a TWRP running on my Pixel 4a! It even decrypts my profile!
However I only `fastboot boot boot.img` it, never burned into slot. My device uses verified boot and I would like to continue to use it. Can I sign the image so it will be safe to be stored there?

I also replaced with my kernel parts inside `device/google/sunfish-kernel/`.

**Comment by strlcat** [comment]
No worries, I am going to use it temporarily booting with fastboot. Many thanks for your work!
